n=int(input('Enter no. of elements:'))
l=[]
for i in range(n):
    a=int(input('Enter element:'))
    l.append(a)
print(l)
l.sort()
print(l)
print(l.count(2))
l.pop(2)
print(l)
l.remove(2)
print(l)
l.insert(2,9)
l.extend([7,8,9])
print(l)
print(sum(l))
print(max(l))
print(min(l))
print(1 not in l)